//! Deadline queue shared by the rights' forfeit sweeps.
//!
//! Entries wait in hour buckets by deadline. A bitmap trie over the bucket ids finds
//! the earliest bucket, and a cursor resumes a bucket that one block could not finish.
//! A contract keeps the columns and exposes them through an adapter generated by
//! [`impl_expiry_queue!`](crate::impl_expiry_queue).

use std::marker::PhantomData;

use alloy_primitives::{keccak256, B256, U256};

use crate::error::Result;
use crate::math::tree_math::{self, BinTreeStorage};
use crate::storage::dsl::{Map, Value};
use crate::storage::types::{Storable, StorageKey};

pub const BUCKET_SECONDS: u64 = 3_600;

/// A queue entry. The zero value marks a vacant slot.
pub trait QueueEntry: Copy + PartialEq + Storable + StorageKey {
    fn is_vacant(&self) -> bool;
}

impl QueueEntry for U256 {
    fn is_vacant(&self) -> bool {
        self.is_zero()
    }
}

impl QueueEntry for B256 {
    fn is_vacant(&self) -> bool {
        self.is_zero()
    }
}

impl QueueEntry for u64 {
    fn is_vacant(&self) -> bool {
        *self == 0
    }
}

/// The columns one contract keeps for its queue.
pub trait ExpiryQueueStore<'storage>: BinTreeStorage {
    type Entry: QueueEntry;

    /// Slots ever used in a bucket. Freed slots are zeroed in place, not compacted.
    fn bucket_len(&self) -> &Map<'storage, u32, u32>;
    fn bucket_live(&self) -> &Map<'storage, u32, u32>;
    /// [`slot_key`] -> entry.
    fn bucket_at(&self) -> &Map<'storage, B256, Self::Entry>;
    /// Entry -> [`pack_slot`]. 0 means not queued.
    fn entry_slot(&self) -> &Map<'storage, Self::Entry, u64>;
    fn entry_deadline(&self) -> &Map<'storage, Self::Entry, u64>;
    fn sweep_bucket(&self) -> &Value<'storage, u32>;
    fn sweep_cursor(&self) -> &Value<'storage, u32>;
}

/// Hour since the epoch that a deadline falls in.
pub const fn bucket_of(timestamp: u64) -> u32 {
    (timestamp / BUCKET_SECONDS) as u32
}

pub const fn bucket_end(bucket: u32) -> u64 {
    (bucket as u64 + 1) * BUCKET_SECONDS
}

pub const fn pack_slot(bucket: u32, slot: u32) -> u64 {
    ((bucket as u64) << 32) | slot as u64
}

pub const fn unpack_slot(packed: u64) -> (u32, u32) {
    ((packed >> 32) as u32, (packed & 0xffff_ffff) as u32)
}

pub fn slot_key(bucket: u32, slot: u32) -> B256 {
    let mut buf = [0u8; 8];
    buf[0..4].copy_from_slice(&bucket.to_be_bytes());
    buf[4..8].copy_from_slice(&slot.to_be_bytes());
    keccak256(buf)
}

/// Appends `entry` to `bucket` and records the slot it took.
pub fn place<'s, Q: ExpiryQueueStore<'s>>(queue: &Q, entry: Q::Entry, bucket: u32) -> Result<()> {
    let slot = queue.bucket_len().read(&bucket)?;
    queue.bucket_at().write(&slot_key(bucket, slot), entry)?;
    queue.bucket_len().write(&bucket, slot.saturating_add(1))?;
    queue.entry_slot().write(&entry, pack_slot(bucket, slot))?;

    let live = queue.bucket_live().read(&bucket)?;
    queue.bucket_live().write(&bucket, live.saturating_add(1))?;
    if live == 0 {
        tree_math::add(queue, bucket)?;
    }
    Ok(())
}

/// Queues `entry` in the bucket of its deadline.
pub fn push<'s, Q: ExpiryQueueStore<'s>>(queue: &Q, entry: Q::Entry, deadline: u64) -> Result<()> {
    place(queue, entry, bucket_of(deadline))?;
    queue.entry_deadline().write(&entry, deadline)
}

/// Drops `entry` and its deadline from the queue.
pub fn remove<'s, Q: ExpiryQueueStore<'s>>(queue: &Q, entry: Q::Entry) -> Result<()> {
    let packed = queue.entry_slot().read(&entry)?;
    queue.entry_slot().clear(&entry)?;
    queue.entry_deadline().clear(&entry)?;
    if packed == 0 {
        return Ok(());
    }
    let (bucket, slot) = unpack_slot(packed);
    release(queue, bucket, slot, entry)
}

/// Moves `entry` to `bucket`. Its deadline does not change.
pub fn retarget<'s, Q: ExpiryQueueStore<'s>>(
    queue: &Q,
    entry: Q::Entry,
    bucket: u32,
) -> Result<()> {
    let packed = queue.entry_slot().read(&entry)?;
    if packed != 0 {
        let (old_bucket, old_slot) = unpack_slot(packed);
        release(queue, old_bucket, old_slot, entry)?;
    }
    place(queue, entry, bucket)
}

/// Frees one slot, and retires the bucket once nothing waits in it.
pub fn release<'s, Q: ExpiryQueueStore<'s>>(
    queue: &Q,
    bucket: u32,
    slot: u32,
    entry: Q::Entry,
) -> Result<()> {
    let key = slot_key(bucket, slot);
    if queue.bucket_at().read(&key)? != entry {
        return Ok(());
    }
    queue.bucket_at().clear(&key)?;

    let live = queue.bucket_live().read(&bucket)?.saturating_sub(1);
    queue.bucket_live().write(&bucket, live)?;
    if live == 0 {
        queue.bucket_len().clear(&bucket)?;
        queue.bucket_live().clear(&bucket)?;
        tree_math::remove(queue, bucket)?;
        // A refill of the bucket must not resume past its new end.
        if queue.sweep_bucket().read()? == bucket {
            queue.sweep_bucket().write(0)?;
            queue.sweep_cursor().write(0)?;
        }
    }
    Ok(())
}

pub fn entry_at<'s, Q: ExpiryQueueStore<'s>>(
    queue: &Q,
    bucket: u32,
    slot: u32,
) -> Result<Option<Q::Entry>> {
    let entry = queue.bucket_at().read(&slot_key(bucket, slot))?;
    Ok((!entry.is_vacant()).then_some(entry))
}

pub fn first_bucket<'s, Q: ExpiryQueueStore<'s>>(queue: &Q) -> Result<Option<u32>> {
    tree_math::find_first_left_inclusive(queue, 0)
}

/// Clears a bucket the sweep has walked to its end.
pub fn retire_bucket<'s, Q: ExpiryQueueStore<'s>>(queue: &Q, bucket: u32) -> Result<()> {
    queue.bucket_len().clear(&bucket)?;
    queue.bucket_live().clear(&bucket)?;
    tree_math::remove(queue, bucket)?;
    if queue.sweep_bucket().read()? == bucket {
        queue.sweep_bucket().write(0)?;
        queue.sweep_cursor().write(0)?;
    }
    Ok(())
}

/// What expiring one due entry did to the walk.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Step {
    /// The walk moves to the next slot.
    Done,
    /// The walk ends here and resumes at this slot.
    Hold,
}

/// A right's handling of its due entries.
pub trait ExpiryHandler<E> {
    /// Expires a due entry and charges `budget` for the work.
    fn expire(&mut self, entry: E, budget: &mut u32) -> Result<Step>;
    /// Handles an entry still live in a bucket the walk has finished.
    fn retire_leftover(&mut self, entry: E) -> Result<()>;
}

/// Expires due entries, earliest bucket first. A slot that is vacant or not due
/// costs one unit of `budget`. The handler charges for the entries it expires.
pub fn sweep<'s, Q, H>(queue: &Q, now: u64, budget: &mut u32, handler: &mut H) -> Result<()>
where
    Q: ExpiryQueueStore<'s>,
    H: ExpiryHandler<Q::Entry>,
{
    let mut walk = Walk {
        queue,
        now,
        budget,
        handler,
        storage: PhantomData,
    };
    while *walk.budget > 0 {
        let Some(bucket) = first_bucket(queue)? else {
            break;
        };
        // A deadline lies inside its own bucket, so an open one holds nobody due.
        if now < bucket_end(bucket) || !walk.bucket(bucket)? {
            break;
        }
    }
    Ok(())
}

/// One block's walk over the due buckets.
struct Walk<'w, 's, Q, H> {
    queue: &'w Q,
    now: u64,
    budget: &'w mut u32,
    handler: &'w mut H,
    storage: PhantomData<&'s ()>,
}

impl<'s, Q, H> Walk<'_, 's, Q, H>
where
    Q: ExpiryQueueStore<'s>,
    H: ExpiryHandler<Q::Entry>,
{
    /// Returns false when the bucket still needs another block's budget.
    fn bucket(&mut self, bucket: u32) -> Result<bool> {
        let len = self.queue.bucket_len().read(&bucket)?;
        let slot = self.walk_slots(bucket, len)?;
        // The last live entry left and retired the bucket, cursor included.
        if self.queue.bucket_live().read(&bucket)? == 0 {
            return Ok(true);
        }
        if slot < len {
            self.queue.sweep_bucket().write(bucket)?;
            self.queue.sweep_cursor().write(slot)?;
            return Ok(false);
        }
        self.queue.sweep_bucket().write(0)?;
        self.queue.sweep_cursor().write(0)?;
        for slot in 0..len {
            if let Some(entry) = entry_at(self.queue, bucket, slot)? {
                self.handler.retire_leftover(entry)?;
            }
        }
        retire_bucket(self.queue, bucket)?;
        Ok(true)
    }

    /// Walks the bucket from its cursor. Returns the slot the walk stopped at.
    fn walk_slots(&mut self, bucket: u32, len: u32) -> Result<u32> {
        let mut slot = match self.queue.sweep_bucket().read()? == bucket {
            true => self.queue.sweep_cursor().read()?.min(len),
            false => 0,
        };
        while slot < len && *self.budget > 0 {
            match self.visit(bucket, slot)? {
                None => slot += 1,
                Some(Step::Hold) => break,
                Some(Step::Done) => {
                    slot += 1;
                    if self.queue.bucket_live().read(&bucket)? == 0 {
                        break;
                    }
                }
            }
        }
        Ok(slot)
    }

    /// Expires the slot's entry if it is due. `None` means the slot was vacant or not due.
    fn visit(&mut self, bucket: u32, slot: u32) -> Result<Option<Step>> {
        let due = match entry_at(self.queue, bucket, slot)? {
            Some(entry) if self.now > self.queue.entry_deadline().read(&entry)? => Some(entry),
            _ => None,
        };
        let Some(entry) = due else {
            *self.budget -= 1;
            return Ok(None);
        };
        self.handler.expire(entry, self.budget).map(Some)
    }
}

/// Implements [`BinTreeStorage`] and [`ExpiryQueueStore`] for `Adapter(&contract)`.
#[macro_export]
macro_rules! impl_expiry_queue {
    ($adapter:ident<$entry:ty> {
        root: $root:ident,
        mid: $mid:ident,
        leaf: $leaf:ident,
        len: $len:ident,
        live: $live:ident,
        at: $at:ident,
        slot: $slot:ident,
        deadline: $deadline:ident,
        sweep_bucket: $sweep_bucket:ident,
        cursor: $cursor:ident $(,)?
    }) => {
        $crate::impl_bin_tree_storage!($adapter {
            root: $root,
            mid: $mid,
            leaf: $leaf,
        });

        impl<'s> $crate::expiry_queue::ExpiryQueueStore<'s> for $adapter<'_, 's> {
            type Entry = $entry;
            fn bucket_len(&self) -> &$crate::storage::dsl::Map<'s, u32, u32> {
                &self.0.$len
            }
            fn bucket_live(&self) -> &$crate::storage::dsl::Map<'s, u32, u32> {
                &self.0.$live
            }
            fn bucket_at(
                &self,
            ) -> &$crate::storage::dsl::Map<'s, ::alloy_primitives::B256, $entry> {
                &self.0.$at
            }
            fn entry_slot(&self) -> &$crate::storage::dsl::Map<'s, $entry, u64> {
                &self.0.$slot
            }
            fn entry_deadline(&self) -> &$crate::storage::dsl::Map<'s, $entry, u64> {
                &self.0.$deadline
            }
            fn sweep_bucket(&self) -> &$crate::storage::dsl::Value<'s, u32> {
                &self.0.$sweep_bucket
            }
            fn sweep_cursor(&self) -> &$crate::storage::dsl::Value<'s, u32> {
                &self.0.$cursor
            }
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::{hashmap::HashMapStorageProvider, StorageHandle};
    use alloy_primitives::{address, Address};

    const CONTRACT: Address = address!("0x0000000000000000000000000000000000001003");
    const HOUR: u64 = BUCKET_SECONDS;

    struct Columns<'s> {
        root: Value<'s, U256>,
        mid: Map<'s, u32, U256>,
        leaf: Map<'s, u32, U256>,
        len: Map<'s, u32, u32>,
        live: Map<'s, u32, u32>,
        at: Map<'s, B256, U256>,
        slot: Map<'s, U256, u64>,
        deadline: Map<'s, U256, u64>,
        sweep_bucket: Value<'s, u32>,
        cursor: Value<'s, u32>,
    }

    impl<'s> Columns<'s> {
        fn new(storage: StorageHandle<'s>) -> Self {
            let slot = |n: u64| U256::from(n);
            Self {
                root: Value::new(slot(0), CONTRACT, storage.clone()),
                mid: Map::new(slot(1), CONTRACT, storage.clone()),
                leaf: Map::new(slot(2), CONTRACT, storage.clone()),
                len: Map::new(slot(3), CONTRACT, storage.clone()),
                live: Map::new(slot(4), CONTRACT, storage.clone()),
                at: Map::new(slot(5), CONTRACT, storage.clone()),
                slot: Map::new(slot(6), CONTRACT, storage.clone()),
                deadline: Map::new(slot(7), CONTRACT, storage.clone()),
                sweep_bucket: Value::new(slot(8), CONTRACT, storage.clone()),
                cursor: Value::new(slot(9), CONTRACT, storage),
            }
        }
    }

    struct Queue<'a, 's>(&'a Columns<'s>);

    crate::impl_expiry_queue!(Queue<U256> {
        root: root,
        mid: mid,
        leaf: leaf,
        len: len,
        live: live,
        at: at,
        slot: slot,
        deadline: deadline,
        sweep_bucket: sweep_bucket,
        cursor: cursor,
    });

    /// Expires an entry for one budget unit, or holds on the entries it is told to.
    struct Recorder<'a, 's> {
        queue: &'a Queue<'a, 's>,
        expired: Vec<U256>,
        retired: Vec<U256>,
        hold_on: Vec<U256>,
    }

    impl ExpiryHandler<U256> for Recorder<'_, '_> {
        fn expire(&mut self, entry: U256, budget: &mut u32) -> Result<Step> {
            if self.hold_on.contains(&entry) {
                return Ok(Step::Hold);
            }
            *budget -= 1;
            self.expired.push(entry);
            remove(self.queue, entry)?;
            Ok(Step::Done)
        }

        fn retire_leftover(&mut self, entry: U256) -> Result<()> {
            self.retired.push(entry);
            remove(self.queue, entry)
        }
    }

    fn with_queue(test: impl FnOnce(&Queue<'_, '_>)) {
        let mut provider = HashMapStorageProvider::new(1);
        StorageHandle::enter(&mut provider, |storage| {
            let columns = Columns::new(storage);
            test(&Queue(&columns));
        });
    }

    fn recorder<'a, 's>(queue: &'a Queue<'a, 's>) -> Recorder<'a, 's> {
        Recorder {
            queue,
            expired: Vec::new(),
            retired: Vec::new(),
            hold_on: Vec::new(),
        }
    }

    fn id(n: u64) -> U256 {
        U256::from(n)
    }

    #[test]
    fn removing_the_last_entry_retires_its_bucket_and_cursor() {
        with_queue(|queue| {
            push(queue, id(1), 10 * HOUR + 5).unwrap();
            push(queue, id(2), 10 * HOUR + 9).unwrap();
            assert_eq!(first_bucket(queue).unwrap(), Some(10));
            queue.sweep_bucket().write(10).unwrap();
            queue.sweep_cursor().write(1).unwrap();

            remove(queue, id(1)).unwrap();
            assert_eq!(queue.bucket_live().read(&10).unwrap(), 1);
            assert_eq!(entry_at(queue, 10, 0).unwrap(), None);
            remove(queue, id(2)).unwrap();

            assert_eq!(first_bucket(queue).unwrap(), None);
            assert_eq!(queue.bucket_len().read(&10).unwrap(), 0);
            assert_eq!(queue.sweep_bucket().read().unwrap(), 0);
            assert_eq!(queue.sweep_cursor().read().unwrap(), 0);
            assert_eq!(queue.entry_deadline().read(&id(1)).unwrap(), 0);
        });
    }

    #[test]
    fn retargeting_moves_the_entry_and_keeps_its_deadline() {
        with_queue(|queue| {
            push(queue, id(1), 10 * HOUR).unwrap();
            retarget(queue, id(1), 12).unwrap();
            assert_eq!(first_bucket(queue).unwrap(), Some(12));
            assert_eq!(entry_at(queue, 12, 0).unwrap(), Some(id(1)));
            assert_eq!(queue.entry_deadline().read(&id(1)).unwrap(), 10 * HOUR);
            assert_eq!(queue.bucket_live().read(&10).unwrap(), 0);
        });
    }

    #[test]
    fn a_sweep_expires_due_entries_earliest_bucket_first_and_stops_at_an_open_one() {
        with_queue(|queue| {
            push(queue, id(3), 12 * HOUR).unwrap();
            push(queue, id(1), 10 * HOUR).unwrap();
            push(queue, id(2), 11 * HOUR).unwrap();
            let mut handler = recorder(queue);
            let mut budget = 10;
            sweep(queue, 12 * HOUR + 10, &mut budget, &mut handler).unwrap();
            assert_eq!(handler.expired, vec![id(1), id(2)]);
            assert_eq!(budget, 8);
            assert_eq!(first_bucket(queue).unwrap(), Some(12));
        });
    }

    #[test]
    fn a_slot_not_yet_due_costs_one_and_stays_queued_until_retired() {
        with_queue(|queue| {
            push(queue, id(1), 10 * HOUR + 100).unwrap();
            push(queue, id(2), 10 * HOUR + 10).unwrap();
            let mut handler = recorder(queue);
            let mut budget = 10;
            // At the deadline itself the entry is not due yet.
            sweep(queue, 10 * HOUR + 100, &mut budget, &mut handler).unwrap();
            assert_eq!(handler.expired, Vec::<U256>::new());
            assert_eq!(budget, 10, "an open bucket is not walked");

            sweep(queue, 11 * HOUR, &mut budget, &mut handler).unwrap();
            assert_eq!(handler.expired, vec![id(1), id(2)]);
            assert_eq!(budget, 8);
        });
    }

    #[test]
    fn a_spent_budget_resumes_at_the_cursor() {
        with_queue(|queue| {
            for n in 1..=3 {
                push(queue, id(n), 10 * HOUR).unwrap();
            }
            let mut handler = recorder(queue);
            let mut budget = 2;
            sweep(queue, 11 * HOUR, &mut budget, &mut handler).unwrap();
            assert_eq!(handler.expired, vec![id(1), id(2)]);
            assert_eq!(queue.sweep_bucket().read().unwrap(), 10);
            assert_eq!(queue.sweep_cursor().read().unwrap(), 2);

            let mut budget = 2;
            sweep(queue, 11 * HOUR, &mut budget, &mut handler).unwrap();
            assert_eq!(handler.expired, vec![id(1), id(2), id(3)]);
            assert_eq!(first_bucket(queue).unwrap(), None);
        });
    }

    #[test]
    fn a_hold_keeps_the_cursor_on_its_slot_and_ends_the_pass() {
        with_queue(|queue| {
            push(queue, id(1), 10 * HOUR).unwrap();
            push(queue, id(2), 10 * HOUR).unwrap();
            push(queue, id(3), 11 * HOUR).unwrap();
            let mut handler = recorder(queue);
            handler.hold_on.push(id(2));
            let mut budget = 10;
            sweep(queue, 12 * HOUR, &mut budget, &mut handler).unwrap();
            assert_eq!(handler.expired, vec![id(1)]);
            assert_eq!(queue.sweep_bucket().read().unwrap(), 10);
            assert_eq!(queue.sweep_cursor().read().unwrap(), 1);

            handler.hold_on.clear();
            sweep(queue, 12 * HOUR, &mut budget, &mut handler).unwrap();
            assert_eq!(handler.expired, vec![id(1), id(2), id(3)]);
        });
    }

    #[test]
    fn an_entry_left_in_a_walked_bucket_is_retired() {
        with_queue(|queue| {
            push(queue, id(1), 10 * HOUR).unwrap();
            // A deadline past the bucket's end breaks the invariant the walk relies on.
            place(queue, id(2), 10).unwrap();
            queue.entry_deadline().write(&id(2), 20 * HOUR).unwrap();
            let mut handler = recorder(queue);
            let mut budget = 10;
            sweep(queue, 11 * HOUR, &mut budget, &mut handler).unwrap();
            assert_eq!(handler.expired, vec![id(1)]);
            assert_eq!(handler.retired, vec![id(2)]);
            assert_eq!(first_bucket(queue).unwrap(), None);
            assert_eq!(queue.sweep_bucket().read().unwrap(), 0);
        });
    }
}
