//! Deadline queue shared by the rights' forfeit sweeps.
//!
//! Entries wait in hour buckets by deadline. A bitmap trie over the bucket ids finds
//! the earliest bucket, and a cursor resumes a bucket that one block could not finish.
//! A contract keeps the columns and exposes them through an adapter generated by
//! [`impl_expiry_queue!`](crate::impl_expiry_queue).

use alloy_primitives::{keccak256, B256, U256};

use crate::error::{decide, Decided, PrecompileError, Result, SweepFailure};
use crate::math::tree_math::{self, BinTreeStorage};
use crate::storage::dsl::{Map, Value};
use crate::storage::types::{Storable, StorageKey};
use crate::storage::StorageHandle;
use crate::sweep_budget::SweepBudget;

pub const BUCKET_SECONDS: u64 = 3_600;

/// A queue entry. The zero value marks a vacant slot.
pub trait QueueEntry: Copy + PartialEq + Storable + StorageKey {
    fn is_vacant(&self) -> bool;
}

impl QueueEntry for U256 {
    fn is_vacant(&self) -> bool {
        self.is_zero()
    }
}

impl QueueEntry for B256 {
    fn is_vacant(&self) -> bool {
        self.is_zero()
    }
}

impl QueueEntry for u64 {
    fn is_vacant(&self) -> bool {
        *self == 0
    }
}

/// The columns one contract keeps for its queue.
pub trait ExpiryQueueStore<'storage>: BinTreeStorage {
    type Entry: QueueEntry;

    /// Slots ever used in a bucket. Freed slots are zeroed in place, not compacted.
    fn bucket_len(&self) -> &Map<'storage, u32, u32>;
    fn bucket_live(&self) -> &Map<'storage, u32, u32>;
    /// [`slot_key`] -> entry.
    fn bucket_at(&self) -> &Map<'storage, B256, Self::Entry>;
    /// Entry -> [`pack_slot`]. 0 means not queued.
    fn entry_slot(&self) -> &Map<'storage, Self::Entry, u64>;
    fn entry_deadline(&self) -> &Map<'storage, Self::Entry, u64>;
    fn sweep_bucket(&self) -> &Value<'storage, u32>;
    /// [`pack_cursor`] of where the held walk resumes.
    fn sweep_cursor(&self) -> &Value<'storage, u64>;
}

/// Hour since the epoch that a deadline falls in.
pub const fn bucket_of(timestamp: u64) -> u32 {
    (timestamp / BUCKET_SECONDS) as u32
}

pub const fn bucket_end(bucket: u32) -> u64 {
    (bucket as u64 + 1) * BUCKET_SECONDS
}

pub const fn pack_slot(bucket: u32, slot: u32) -> u64 {
    ((bucket as u64) << 32) | slot as u64
}

pub const fn unpack_slot(packed: u64) -> (u32, u32) {
    ((packed >> 32) as u32, (packed & 0xffff_ffff) as u32)
}

/// The slot a held walk resumes at, and the member below which its entry resumes. Every
/// member from that index up already failed in this pass. 0 means from the top.
pub const fn pack_cursor(slot: u32, member: u32) -> u64 {
    ((slot as u64) << 32) | member as u64
}

pub const fn unpack_cursor(packed: u64) -> (u32, u32) {
    ((packed >> 32) as u32, (packed & 0xffff_ffff) as u32)
}

pub fn slot_key(bucket: u32, slot: u32) -> B256 {
    let mut buf = [0u8; 8];
    buf[0..4].copy_from_slice(&bucket.to_be_bytes());
    buf[4..8].copy_from_slice(&slot.to_be_bytes());
    keccak256(buf)
}

/// Appends `entry` to `bucket` and records the slot it took.
pub fn place<'s, Q: ExpiryQueueStore<'s>>(queue: &Q, entry: Q::Entry, bucket: u32) -> Result<()> {
    let slot = queue.bucket_len().read(&bucket)?;
    queue.bucket_at().write(&slot_key(bucket, slot), entry)?;
    queue.bucket_len().write(&bucket, slot.saturating_add(1))?;
    queue.entry_slot().write(&entry, pack_slot(bucket, slot))?;

    let live = queue.bucket_live().read(&bucket)?;
    queue.bucket_live().write(&bucket, live.saturating_add(1))?;
    if live == 0 {
        tree_math::add(queue, bucket)?;
    }
    Ok(())
}

/// Queues `entry` in the bucket of its deadline.
pub fn push<'s, Q: ExpiryQueueStore<'s>>(queue: &Q, entry: Q::Entry, deadline: u64) -> Result<()> {
    place(queue, entry, bucket_of(deadline))?;
    queue.entry_deadline().write(&entry, deadline)
}

/// Drops `entry` and its deadline from the queue.
pub fn remove<'s, Q: ExpiryQueueStore<'s>>(queue: &Q, entry: Q::Entry) -> Result<()> {
    let packed = queue.entry_slot().read(&entry)?;
    queue.entry_slot().clear(&entry)?;
    queue.entry_deadline().clear(&entry)?;
    if packed == 0 {
        return Ok(());
    }
    let (bucket, slot) = unpack_slot(packed);
    release(queue, bucket, slot, entry)
}

/// Moves `entry` to `bucket`. Its deadline does not change.
pub fn retarget<'s, Q: ExpiryQueueStore<'s>>(
    queue: &Q,
    entry: Q::Entry,
    bucket: u32,
) -> Result<()> {
    let packed = queue.entry_slot().read(&entry)?;
    if packed != 0 {
        let (old_bucket, old_slot) = unpack_slot(packed);
        release(queue, old_bucket, old_slot, entry)?;
    }
    place(queue, entry, bucket)
}

/// Frees one slot, and retires the bucket once nothing waits in it.
pub fn release<'s, Q: ExpiryQueueStore<'s>>(
    queue: &Q,
    bucket: u32,
    slot: u32,
    entry: Q::Entry,
) -> Result<()> {
    let key = slot_key(bucket, slot);
    if queue.bucket_at().read(&key)? != entry {
        return Ok(());
    }
    queue.bucket_at().clear(&key)?;

    let live = queue.bucket_live().read(&bucket)?.saturating_sub(1);
    queue.bucket_live().write(&bucket, live)?;
    if live == 0 {
        queue.bucket_len().clear(&bucket)?;
        queue.bucket_live().clear(&bucket)?;
        tree_math::remove(queue, bucket)?;
        // A refill of the bucket must not resume past its new end.
        if queue.sweep_bucket().read()? == bucket {
            queue.sweep_bucket().write(0)?;
            queue.sweep_cursor().write(0)?;
        }
    }
    Ok(())
}

pub fn entry_at<'s, Q: ExpiryQueueStore<'s>>(
    queue: &Q,
    bucket: u32,
    slot: u32,
) -> Result<Option<Q::Entry>> {
    let entry = queue.bucket_at().read(&slot_key(bucket, slot))?;
    Ok((!entry.is_vacant()).then_some(entry))
}

pub fn first_bucket<'s, Q: ExpiryQueueStore<'s>>(queue: &Q) -> Result<Option<u32>> {
    tree_math::find_first_left_inclusive(queue, 0)
}

/// Clears a bucket the sweep has walked to its end.
pub fn retire_bucket<'s, Q: ExpiryQueueStore<'s>>(queue: &Q, bucket: u32) -> Result<()> {
    queue.bucket_len().clear(&bucket)?;
    queue.bucket_live().clear(&bucket)?;
    tree_math::remove(queue, bucket)?;
    if queue.sweep_bucket().read()? == bucket {
        queue.sweep_bucket().write(0)?;
        queue.sweep_cursor().write(0)?;
    }
    Ok(())
}

/// What expiring one due entry did to the walk.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Step {
    /// The walk moves to the next slot.
    Done,
    /// The walk ends here and resumes at this slot, below this member.
    Hold(u32),
}

/// What a right makes of a due entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Due {
    /// Expire its members.
    Expire,
    /// Nothing is left to expire: the entry leaves the queue.
    Drop,
    /// Not yet: the entry waits for a later hour.
    Wait,
}

/// A right's handling of its due entries. The queue owns the policy: each member
/// expires in its own checkpoint, a failure classified as deterministic leaves the
/// member in place and defers the entry once every member was tried, running out of
/// budget or gas resumes on the entry next block below the members already tried,
/// and anything node-local fails the block.
pub trait ExpiryHandler<E> {
    type Member: Copy;

    fn due(&mut self, entry: E) -> Result<Due>;
    fn member_count(&self, entry: E) -> Result<u32>;
    fn member_at(&self, entry: E, index: u32) -> Result<Self::Member>;
    /// Takes what expiring one member costs.
    fn charge(&self, budget: &mut SweepBudget) -> bool {
        budget.write()
    }
    /// Expires `member` and takes it out of the entry.
    fn expire_member(&mut self, entry: E, member: Self::Member) -> Result<()>;
    fn classify(&self, error: &PrecompileError) -> SweepFailure {
        error.sweep_failure()
    }
    /// Reports that the entry waits until `retry_at`.
    fn deferred(&mut self, entry: E, retry_at: u64) -> Result<()>;
}

/// Expires due entries, earliest bucket first. Every slot visited costs a visit,
/// and the handler charges for each member it expires.
pub fn sweep<'s, Q, H>(
    queue: &Q,
    storage: &StorageHandle<'s>,
    now: u64,
    budget: &mut SweepBudget,
    handler: &mut H,
) -> Result<()>
where
    Q: ExpiryQueueStore<'s>,
    H: ExpiryHandler<Q::Entry>,
{
    let mut walk = Walk {
        queue,
        storage,
        now,
        budget,
        handler,
    };
    while walk.budget.visits_left() > 0 {
        let Some(bucket) = first_bucket(queue)? else {
            break;
        };
        // A deadline lies inside its own bucket, so an open one holds nobody due.
        if now < bucket_end(bucket) || !walk.bucket(bucket)? {
            break;
        }
    }
    Ok(())
}

/// One block's walk over the due buckets.
struct Walk<'w, 's, Q, H> {
    queue: &'w Q,
    storage: &'w StorageHandle<'s>,
    now: u64,
    budget: &'w mut SweepBudget,
    handler: &'w mut H,
}

impl<'s, Q, H> Walk<'_, 's, Q, H>
where
    Q: ExpiryQueueStore<'s>,
    H: ExpiryHandler<Q::Entry>,
{
    /// Returns false when the bucket still needs another block's budget.
    fn bucket(&mut self, bucket: u32) -> Result<bool> {
        let len = self.queue.bucket_len().read(&bucket)?;
        let (slot, member) = self.walk_slots(bucket, len)?;
        // The last live entry left and retired the bucket, cursor included.
        if self.queue.bucket_live().read(&bucket)? == 0 {
            return Ok(true);
        }
        if slot < len {
            self.queue.sweep_bucket().write(bucket)?;
            self.queue.sweep_cursor().write(pack_cursor(slot, member))?;
            return Ok(false);
        }
        self.queue.sweep_bucket().write(0)?;
        self.queue.sweep_cursor().write(0)?;
        for slot in 0..len {
            if let Some(entry) = entry_at(self.queue, bucket, slot)? {
                self.retire_leftover(entry)?;
            }
        }
        retire_bucket(self.queue, bucket)?;
        Ok(true)
    }

    /// Walks the bucket from its cursor. Returns the slot the walk stopped at, and the
    /// member its entry resumes below.
    fn walk_slots(&mut self, bucket: u32, len: u32) -> Result<(u32, u32)> {
        let (mut slot, mut member) = match self.queue.sweep_bucket().read()? == bucket {
            true => unpack_cursor(self.queue.sweep_cursor().read()?),
            false => (0, 0),
        };
        while slot < len && self.budget.visit() {
            match self.visit(bucket, slot, member)? {
                None => slot += 1,
                Some(Step::Hold(held)) => return Ok((slot, held)),
                Some(Step::Done) => {
                    slot += 1;
                    if self.queue.bucket_live().read(&bucket)? == 0 {
                        break;
                    }
                }
            }
            member = 0;
        }
        Ok((slot, 0))
    }

    /// Expires the slot's entry if it is due. `None` means the slot was vacant or not due.
    fn visit(&mut self, bucket: u32, slot: u32, member: u32) -> Result<Option<Step>> {
        match entry_at(self.queue, bucket, slot)? {
            Some(entry) if self.now > self.queue.entry_deadline().read(&entry)? => {
                self.expire(entry, member).map(Some)
            }
            _ => Ok(None),
        }
    }

    fn expire(&mut self, entry: Q::Entry, resume: u32) -> Result<Step> {
        match self.handler.due(entry)? {
            Due::Expire => {}
            Due::Drop => {
                self.drop_entry(entry)?;
                return Ok(Step::Done);
            }
            Due::Wait => {
                self.defer(entry)?;
                return Ok(Step::Done);
            }
        }
        // From the last member down, so a member that swap-removes itself only moves
        // one already tried, and the members from `index` up are the ones that failed.
        let count = self.handler.member_count(entry)?;
        let mut index = match resume {
            0 => count,
            held => held.min(count),
        };
        let mut failed = count - index;
        while index > 0 {
            if !self.handler.charge(self.budget) {
                return Ok(Step::Hold(index));
            }
            index -= 1;
            let member = self.handler.member_at(entry, index)?;
            let handler = &mut *self.handler;
            let outcome = self
                .storage
                .with_checkpoint(|| handler.expire_member(entry, member));
            match decide(outcome, |error| self.handler.classify(error))? {
                Decided::Done(()) => {}
                Decided::Stopped => return Ok(Step::Hold(index + 1)),
                Decided::Skipped(error) => {
                    tracing::warn!(target: "outbe::expiry", error = ?error, "expiry sweep: member left for a later hour");
                    failed += 1;
                }
            }
        }
        match failed {
            0 => self.drop_entry(entry)?,
            _ => self.defer(entry)?,
        }
        Ok(Step::Done)
    }

    /// An entry still live in a walked bucket waits for a later hour, or leaves.
    fn retire_leftover(&mut self, entry: Q::Entry) -> Result<()> {
        match self.handler.due(entry)? {
            Due::Drop => self.drop_entry(entry),
            Due::Expire | Due::Wait => self.defer(entry),
        }
    }

    /// Takes the entry out of the queue as one step.
    fn drop_entry(&mut self, entry: Q::Entry) -> Result<()> {
        let queue = self.queue;
        self.storage.with_checkpoint(|| remove(queue, entry))
    }

    /// Moves the entry to its deadline's hour, never before the next one, as one step.
    fn defer(&mut self, entry: Q::Entry) -> Result<()> {
        let deadline = self.queue.entry_deadline().read(&entry)?;
        let bucket = bucket_of(deadline).max(bucket_of(self.now).saturating_add(1));
        let (queue, handler) = (self.queue, &mut *self.handler);
        self.storage.with_checkpoint(|| {
            retarget(queue, entry, bucket)?;
            handler.deferred(entry, bucket_end(bucket))
        })
    }
}

/// Implements [`BinTreeStorage`] and [`ExpiryQueueStore`] for `Adapter(&contract)`.
#[macro_export]
macro_rules! impl_expiry_queue {
    ($adapter:ident<$entry:ty> {
        root: $root:ident,
        mid: $mid:ident,
        leaf: $leaf:ident,
        len: $len:ident,
        live: $live:ident,
        at: $at:ident,
        slot: $slot:ident,
        deadline: $deadline:ident,
        sweep_bucket: $sweep_bucket:ident,
        cursor: $cursor:ident $(,)?
    }) => {
        $crate::impl_bin_tree_storage!($adapter {
            root: $root,
            mid: $mid,
            leaf: $leaf,
        });

        impl<'s> $crate::expiry_queue::ExpiryQueueStore<'s> for $adapter<'_, 's> {
            type Entry = $entry;
            fn bucket_len(&self) -> &$crate::storage::dsl::Map<'s, u32, u32> {
                &self.0.$len
            }
            fn bucket_live(&self) -> &$crate::storage::dsl::Map<'s, u32, u32> {
                &self.0.$live
            }
            fn bucket_at(
                &self,
            ) -> &$crate::storage::dsl::Map<'s, ::alloy_primitives::B256, $entry> {
                &self.0.$at
            }
            fn entry_slot(&self) -> &$crate::storage::dsl::Map<'s, $entry, u64> {
                &self.0.$slot
            }
            fn entry_deadline(&self) -> &$crate::storage::dsl::Map<'s, $entry, u64> {
                &self.0.$deadline
            }
            fn sweep_bucket(&self) -> &$crate::storage::dsl::Value<'s, u32> {
                &self.0.$sweep_bucket
            }
            fn sweep_cursor(&self) -> &$crate::storage::dsl::Value<'s, u64> {
                &self.0.$cursor
            }
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::{hashmap::HashMapStorageProvider, StorageHandle};
    use alloy_primitives::{address, Address};

    const CONTRACT: Address = address!("0x0000000000000000000000000000000000001003");
    const HOUR: u64 = BUCKET_SECONDS;

    struct Columns<'s> {
        root: Value<'s, U256>,
        mid: Map<'s, u32, U256>,
        leaf: Map<'s, u32, U256>,
        len: Map<'s, u32, u32>,
        live: Map<'s, u32, u32>,
        at: Map<'s, B256, U256>,
        slot: Map<'s, U256, u64>,
        deadline: Map<'s, U256, u64>,
        sweep_bucket: Value<'s, u32>,
        cursor: Value<'s, u64>,
    }

    impl<'s> Columns<'s> {
        fn new(storage: StorageHandle<'s>) -> Self {
            let slot = |n: u64| U256::from(n);
            Self {
                root: Value::new(slot(0), CONTRACT, storage.clone()),
                mid: Map::new(slot(1), CONTRACT, storage.clone()),
                leaf: Map::new(slot(2), CONTRACT, storage.clone()),
                len: Map::new(slot(3), CONTRACT, storage.clone()),
                live: Map::new(slot(4), CONTRACT, storage.clone()),
                at: Map::new(slot(5), CONTRACT, storage.clone()),
                slot: Map::new(slot(6), CONTRACT, storage.clone()),
                deadline: Map::new(slot(7), CONTRACT, storage.clone()),
                sweep_bucket: Value::new(slot(8), CONTRACT, storage.clone()),
                cursor: Value::new(slot(9), CONTRACT, storage),
            }
        }
    }

    struct Queue<'a, 's>(&'a Columns<'s>);

    crate::impl_expiry_queue!(Queue<U256> {
        root: root,
        mid: mid,
        leaf: leaf,
        len: len,
        live: live,
        at: at,
        slot: slot,
        deadline: deadline,
        sweep_bucket: sweep_bucket,
        cursor: cursor,
    });

    /// Each entry is its own single member. It records what the walk did with them.
    struct Recorder {
        expired: Vec<U256>,
        deferred: Vec<(U256, u64)>,
        out_of_gas_on: Vec<U256>,
        refused: Vec<U256>,
        due: Due,
    }

    impl ExpiryHandler<U256> for Recorder {
        type Member = U256;

        fn due(&mut self, _entry: U256) -> Result<Due> {
            Ok(self.due)
        }

        fn member_count(&self, _entry: U256) -> Result<u32> {
            Ok(1)
        }

        fn member_at(&self, entry: U256, _index: u32) -> Result<U256> {
            Ok(entry)
        }

        fn expire_member(&mut self, entry: U256, _member: U256) -> Result<()> {
            if self.out_of_gas_on.contains(&entry) {
                return Err(PrecompileError::OutOfGas);
            }
            if self.refused.contains(&entry) {
                return Err(PrecompileError::Revert("refused".into()));
            }
            self.expired.push(entry);
            Ok(())
        }

        fn deferred(&mut self, entry: U256, retry_at: u64) -> Result<()> {
            self.deferred.push((entry, retry_at));
            Ok(())
        }
    }

    fn with_queue(test: impl for<'s> FnOnce(&Queue<'_, 's>, &StorageHandle<'s>)) {
        let mut provider = HashMapStorageProvider::new(1);
        StorageHandle::enter(&mut provider, |storage| {
            let columns = Columns::new(storage.clone());
            test(&Queue(&columns), &storage);
        });
    }

    fn recorder() -> Recorder {
        Recorder {
            expired: Vec::new(),
            deferred: Vec::new(),
            out_of_gas_on: Vec::new(),
            refused: Vec::new(),
            due: Due::Expire,
        }
    }

    fn id(n: u64) -> U256 {
        U256::from(n)
    }

    fn run<'s>(
        queue: &Queue<'_, 's>,
        storage: &StorageHandle<'s>,
        now: u64,
        budget: &mut SweepBudget,
        handler: &mut Recorder,
    ) {
        sweep(queue, storage, now, budget, handler).unwrap();
    }

    #[test]
    fn removing_the_last_entry_retires_its_bucket_and_cursor() {
        with_queue(|queue, _| {
            push(queue, id(1), 10 * HOUR + 5).unwrap();
            push(queue, id(2), 10 * HOUR + 9).unwrap();
            assert_eq!(first_bucket(queue).unwrap(), Some(10));
            queue.sweep_bucket().write(10).unwrap();
            queue.sweep_cursor().write(1).unwrap();

            remove(queue, id(1)).unwrap();
            assert_eq!(queue.bucket_live().read(&10).unwrap(), 1);
            assert_eq!(entry_at(queue, 10, 0).unwrap(), None);
            remove(queue, id(2)).unwrap();

            assert_eq!(first_bucket(queue).unwrap(), None);
            assert_eq!(queue.bucket_len().read(&10).unwrap(), 0);
            assert_eq!(queue.sweep_bucket().read().unwrap(), 0);
            assert_eq!(queue.sweep_cursor().read().unwrap(), 0);
            assert_eq!(queue.entry_deadline().read(&id(1)).unwrap(), 0);
        });
    }

    #[test]
    fn retargeting_moves_the_entry_and_keeps_its_deadline() {
        with_queue(|queue, _| {
            push(queue, id(1), 10 * HOUR).unwrap();
            retarget(queue, id(1), 12).unwrap();
            assert_eq!(first_bucket(queue).unwrap(), Some(12));
            assert_eq!(entry_at(queue, 12, 0).unwrap(), Some(id(1)));
            assert_eq!(queue.entry_deadline().read(&id(1)).unwrap(), 10 * HOUR);
            assert_eq!(queue.bucket_live().read(&10).unwrap(), 0);
        });
    }

    #[test]
    fn a_sweep_expires_due_entries_earliest_bucket_first_and_stops_at_an_open_one() {
        with_queue(|queue, storage| {
            push(queue, id(3), 12 * HOUR).unwrap();
            push(queue, id(1), 10 * HOUR).unwrap();
            push(queue, id(2), 11 * HOUR).unwrap();
            let mut handler = recorder();
            let mut budget = SweepBudget::new(10, 10, 0);
            run(queue, storage, 12 * HOUR + 10, &mut budget, &mut handler);
            assert_eq!(handler.expired, vec![id(1), id(2)]);
            assert_eq!((budget.visits_left(), budget.writes_left()), (8, 8));
            assert_eq!(first_bucket(queue).unwrap(), Some(12));
        });
    }

    #[test]
    fn a_slot_not_yet_due_stays_queued_until_its_hour_closes() {
        with_queue(|queue, storage| {
            push(queue, id(1), 10 * HOUR + 100).unwrap();
            push(queue, id(2), 10 * HOUR + 10).unwrap();
            let mut handler = recorder();
            let mut budget = SweepBudget::new(10, 10, 0);
            // At the deadline itself the entry is not due yet.
            run(queue, storage, 10 * HOUR + 100, &mut budget, &mut handler);
            assert_eq!(handler.expired, Vec::<U256>::new());
            assert_eq!(budget.visits_left(), 10, "an open bucket is not walked");

            run(queue, storage, 11 * HOUR, &mut budget, &mut handler);
            assert_eq!(handler.expired, vec![id(1), id(2)]);
            assert_eq!(budget.visits_left(), 8);
        });
    }

    #[test]
    fn a_spent_budget_resumes_at_the_cursor() {
        with_queue(|queue, storage| {
            for n in 1..=3 {
                push(queue, id(n), 10 * HOUR).unwrap();
            }
            let mut handler = recorder();
            run(
                queue,
                storage,
                11 * HOUR,
                &mut SweepBudget::new(2, 10, 0),
                &mut handler,
            );
            assert_eq!(handler.expired, vec![id(1), id(2)]);
            assert_eq!(queue.sweep_bucket().read().unwrap(), 10);
            assert_eq!(queue.sweep_cursor().read().unwrap(), pack_cursor(2, 0));

            run(
                queue,
                storage,
                11 * HOUR,
                &mut SweepBudget::new(2, 10, 0),
                &mut handler,
            );
            assert_eq!(handler.expired, vec![id(1), id(2), id(3)]);
            assert_eq!(first_bucket(queue).unwrap(), None);
        });
    }

    #[test]
    fn running_out_of_gas_holds_the_walk_on_its_entry() {
        with_queue(|queue, storage| {
            push(queue, id(1), 10 * HOUR).unwrap();
            push(queue, id(2), 10 * HOUR).unwrap();
            push(queue, id(3), 11 * HOUR).unwrap();
            let mut handler = recorder();
            handler.out_of_gas_on.push(id(2));
            let mut budget = SweepBudget::new(10, 10, 0);
            run(queue, storage, 12 * HOUR, &mut budget, &mut handler);
            assert_eq!(handler.expired, vec![id(1)]);
            assert_eq!(queue.sweep_bucket().read().unwrap(), 10);
            assert_eq!(queue.sweep_cursor().read().unwrap(), pack_cursor(1, 1));

            handler.out_of_gas_on.clear();
            run(queue, storage, 12 * HOUR, &mut budget, &mut handler);
            assert_eq!(handler.expired, vec![id(1), id(2), id(3)]);
        });
    }

    #[test]
    fn a_refused_member_defers_its_entry_and_the_rest_go_on() {
        with_queue(|queue, storage| {
            push(queue, id(1), 10 * HOUR + 5).unwrap();
            push(queue, id(2), 10 * HOUR + 5).unwrap();
            let mut handler = recorder();
            handler.refused.push(id(1));
            let now = 12 * HOUR + 30;
            run(
                queue,
                storage,
                now,
                &mut SweepBudget::new(10, 10, 0),
                &mut handler,
            );
            assert_eq!(handler.expired, vec![id(2)]);
            assert_eq!(handler.deferred, vec![(id(1), 14 * HOUR)]);
            assert_eq!(first_bucket(queue).unwrap(), Some(13));
            assert_eq!(queue.entry_deadline().read(&id(1)).unwrap(), 10 * HOUR + 5);
        });
    }

    /// One entry whose members swap-remove themselves as they expire, as a right's do.
    struct Members {
        members: Vec<u64>,
        failing: Vec<u64>,
        expired: Vec<u64>,
        deferred: u32,
    }

    impl ExpiryHandler<U256> for Members {
        type Member = u32;

        fn due(&mut self, _entry: U256) -> Result<Due> {
            Ok(match self.members.is_empty() {
                true => Due::Drop,
                false => Due::Expire,
            })
        }

        fn member_count(&self, _entry: U256) -> Result<u32> {
            Ok(self.members.len() as u32)
        }

        fn member_at(&self, _entry: U256, index: u32) -> Result<u32> {
            Ok(index)
        }

        fn expire_member(&mut self, _entry: U256, index: u32) -> Result<()> {
            let member = self.members[index as usize];
            if self.failing.contains(&member) {
                return Err(PrecompileError::Revert("refused".into()));
            }
            self.members.swap_remove(index as usize);
            self.expired.push(member);
            Ok(())
        }

        fn deferred(&mut self, _entry: U256, _retry_at: u64) -> Result<()> {
            self.deferred += 1;
            Ok(())
        }
    }

    #[test]
    fn failed_members_wider_than_the_budget_are_tried_once_per_pass() {
        with_queue(|queue, storage| {
            push(queue, id(1), 10 * HOUR).unwrap();
            let mut handler = Members {
                members: (0..10).collect(),
                failing: vec![7, 8, 9],
                expired: Vec::new(),
                deferred: 0,
            };
            for _ in 0..4 {
                sweep(
                    queue,
                    storage,
                    11 * HOUR,
                    &mut SweepBudget::new(10, 2, 0),
                    &mut handler,
                )
                .unwrap();
            }
            assert_eq!(
                handler.expired.len(),
                5,
                "each block gets past the failed members"
            );
            assert_eq!(handler.deferred, 0);

            sweep(
                queue,
                storage,
                11 * HOUR,
                &mut SweepBudget::new(10, 2, 0),
                &mut handler,
            )
            .unwrap();
            assert_eq!(handler.expired.len(), 7);
            assert_eq!(
                handler.deferred, 1,
                "the pass ends and defers the failed members"
            );
            assert_eq!(first_bucket(queue).unwrap(), Some(12));
            assert_eq!(queue.sweep_cursor().read().unwrap(), 0);
        });
    }

    #[test]
    fn an_entry_with_nothing_left_leaves_and_one_not_ready_waits() {
        with_queue(|queue, storage| {
            push(queue, id(1), 10 * HOUR).unwrap();
            let mut handler = recorder();
            handler.due = Due::Drop;
            run(
                queue,
                storage,
                11 * HOUR,
                &mut SweepBudget::new(10, 10, 0),
                &mut handler,
            );
            assert_eq!(first_bucket(queue).unwrap(), None);
            assert_eq!(queue.entry_slot().read(&id(1)).unwrap(), 0);

            push(queue, id(2), 10 * HOUR).unwrap();
            handler.due = Due::Wait;
            run(
                queue,
                storage,
                11 * HOUR,
                &mut SweepBudget::new(10, 10, 0),
                &mut handler,
            );
            assert_eq!(handler.deferred, vec![(id(2), 13 * HOUR)]);
            assert_eq!(first_bucket(queue).unwrap(), Some(12));
            assert!(handler.expired.is_empty());
        });
    }

    #[test]
    fn an_entry_left_in_a_walked_bucket_moves_to_its_deadline_hour() {
        with_queue(|queue, storage| {
            push(queue, id(1), 10 * HOUR).unwrap();
            // A deadline past the bucket's end breaks the invariant the walk relies on.
            place(queue, id(2), 10).unwrap();
            queue.entry_deadline().write(&id(2), 20 * HOUR).unwrap();
            let mut handler = recorder();
            run(
                queue,
                storage,
                11 * HOUR,
                &mut SweepBudget::new(10, 10, 0),
                &mut handler,
            );
            assert_eq!(handler.expired, vec![id(1)]);
            assert_eq!(handler.deferred, vec![(id(2), 21 * HOUR)]);
            assert_eq!(first_bucket(queue).unwrap(), Some(20));
            assert_eq!(queue.sweep_bucket().read().unwrap(), 0);
        });
    }
}
