[package]
name = "outbe-p-link-source-measurements"
version = "0.1.0"
edition = "2021"
publish = false
[workspace]
[dependencies]
outbe-p-link-measurements = { path = "../p-link" }
ark-bn254 = "=0.5.0"
ark-ff = "=0.5.0"
ark-r1cs-std = "=0.5.0"
ark-relations = "=0.5.1"
ark-groth16 = "=0.5.0"
ark-serialize = "=0.5.0"
ark-crypto-primitives = { version = "=0.5.0", features = ["crh", "r1cs"] }
num-bigint = "0.4"
num-traits = "0.2"
rand = "0.8"
sha2 = "0.10"
serde_json = "1"
hex = "0.4"
