// @generated by `cargo xtask ocomp shape`.
// Measurement-only compile ceilings: never an armable network binding.

pub const OCOMP_SHAPE_SCHEMA_VERSION: u16 = 1;
pub const OCOMP_SHAPE_MEASUREMENT_ONLY: bool = true;
pub const OCOMP_SHAPE_ARMABLE: bool = false;
pub const OCOMP_POC_FORK_ID_HEX: &str =
    "1d1378c5bf42070e0326f13d3094f4b7ed3ef42c63edb3179745045f65027eb2";
pub const OCOMP_CORRECTNESS_PROFILE_ID_HEX: &str =
    "0469002bbc5065d8e9d200daede2a65ec479cad78210d7dadabdd5320d241c8d";
pub const OCOMP_CAPACITY_PROFILE_ID_HEX: &str =
    "7c9614691067b57829fba66f37e02860529ab1a24497dbb8f5b53dc5bd0f52df";
pub const OCOMP_SHAPE_GENERATOR_SOURCE_SHA256: &str =
    "8368ca65e2d1e644af2bdb456ca78842b3e4b51becf7ad9650a7c61c4aff0e4d";
pub const OCOMP_SHAPE_INPUT_SET_SHA256: &str =
    "988a733cb23f674f99cb5a1433499a79a9c7c671885c75a3ad34a64868f218a7";
pub const OCOMP_CANDIDATE_LIMITS_SHA256: &str =
    "e52febadeeee298a8d13311bfad3502ff0acb98ee46f05e359e43ea3aed9d281";
pub const OCOMP_MINIMUM_MACHINE_SHA256: &str =
    "335e5f46dbb86ff41a5dcbd164fd681eb79a8a3e3f4880a1af2e42166d824144";
pub const OCOMP_HEADROOM_POLICY_SHA256: &str =
    "ec384d6b098771d4f7dc95f23cbe0995af7aeeae67539cc34151c67023a0516a";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OcompPocCandidateLimitsV1 {
    pub activation_base_gas: u64,
    pub activation_per_action_gas: u64,
    pub activation_per_input_byte_gas: u64,
    pub activation_per_opening_or_proof_byte_gas: u64,
    pub activation_per_signature_gas: u64,
    pub max_action_stream_bytes: u64,
    pub max_activation_calldata_bytes: u64,
    pub max_activation_gas: u64,
    pub max_activation_internal_work: u64,
    pub max_activation_ocb1_bytes: u64,
    pub max_activation_payload_bytes: u64,
    pub max_active_scurve_entries: u64,
    pub max_bounded_result_bytes: u64,
    pub max_bucket_records: u64,
    pub max_ce_mutations: u64,
    pub max_contributor_actions: u64,
    pub max_execution_certificate_bytes: u64,
    pub max_fidelity_openings: u64,
    pub max_finalized_intent_proof_bytes: u64,
    pub max_input_chunk_bytes: u64,
    pub max_input_chunks: u64,
    pub max_input_manifest_bytes: u64,
    pub max_log_bytes: u64,
    pub max_log_count: u64,
    pub max_nod_actions: u64,
    pub max_opening_bytes: u64,
    pub max_oracle_openings: u64,
    pub max_oracle_wwd_pair_entries: u64,
    pub max_poc_tributes: u64,
    pub max_receipt_bytes: u64,
    pub max_signature_verifications: u64,
    pub max_storage_reads: u64,
    pub max_storage_writes: u64,
    pub max_total_units: u64,
    pub max_transaction_rlp_bytes: u64,
    pub max_units_per_phase: u64,
    pub source_retention_after_terminal_blocks: u64,
    pub unit_tributes: u64,
}

pub const OCOMP_POC_CANDIDATE_LIMITS_V1: OcompPocCandidateLimitsV1 = OcompPocCandidateLimitsV1 {
    activation_base_gas: 100000,
    activation_per_action_gas: 25000,
    activation_per_input_byte_gas: 16,
    activation_per_opening_or_proof_byte_gas: 16,
    activation_per_signature_gas: 50000,
    max_action_stream_bytes: 524288,
    max_activation_calldata_bytes: 2097216,
    max_activation_gas: 30000000,
    max_activation_internal_work: 10000000,
    max_activation_ocb1_bytes: 2097152,
    max_activation_payload_bytes: 65536,
    max_active_scurve_entries: 256,
    max_bounded_result_bytes: 1048576,
    max_bucket_records: 256,
    max_ce_mutations: 4096,
    max_contributor_actions: 256,
    max_execution_certificate_bytes: 512,
    max_fidelity_openings: 256,
    max_finalized_intent_proof_bytes: 524288,
    max_input_chunk_bytes: 1048576,
    max_input_chunks: 768,
    max_input_manifest_bytes: 262144,
    max_log_bytes: 65536,
    max_log_count: 8,
    max_nod_actions: 256,
    max_opening_bytes: 262144,
    max_oracle_openings: 256,
    max_oracle_wwd_pair_entries: 256,
    max_poc_tributes: 256,
    max_receipt_bytes: 65536,
    max_signature_verifications: 3,
    max_storage_reads: 8192,
    max_storage_writes: 4096,
    max_total_units: 43,
    max_transaction_rlp_bytes: 2097408,
    max_units_per_phase: 16,
    source_retention_after_terminal_blocks: 64,
    unit_tributes: 32,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OcompPocDevnetMachineV1 {
    pub architecture: &'static str,
    pub operating_system: &'static str,
    pub logical_cpu_count: u64,
    pub nominal_memory_bytes: u64,
    pub minimum_process_memory_bytes: u64,
    pub nominal_root_disk_bytes: u64,
    pub minimum_free_workspace_bytes: u64,
    pub minimum_block_iops: u64,
    pub minimum_block_throughput_bytes_per_second: u64,
    pub init_and_resource_manager: &'static str,
    pub enclave_mode: &'static str,
}

pub const OCOMP_POC_DEVNET_MACHINE_V1: OcompPocDevnetMachineV1 = OcompPocDevnetMachineV1 {
    architecture: "x86_64",
    operating_system: "Ubuntu 24.04",
    init_and_resource_manager: "systemd + unified cgroup v2",
    enclave_mode: "mock Gramine; no SGX claim",
    logical_cpu_count: 4,
    nominal_memory_bytes: 17179869184,
    minimum_process_memory_bytes: 12884901888,
    nominal_root_disk_bytes: 139586437120,
    minimum_free_workspace_bytes: 107374182400,
    minimum_block_iops: 8000,
    minimum_block_throughput_bytes_per_second: 250000000,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OcompPocHeadroomPolicyV1 {
    pub benchmark_cold_runs: u64,
    pub required_headroom_basis_points: u64,
    pub failed_or_timeout_run_rejects_candidate: bool,
    pub retry_failed_run: bool,
}

pub const OCOMP_POC_HEADROOM_POLICY_V1: OcompPocHeadroomPolicyV1 = OcompPocHeadroomPolicyV1 {
    benchmark_cold_runs: 5,
    required_headroom_basis_points: 2000,
    failed_or_timeout_run_rejects_candidate: true,
    retry_failed_run: false,
};
