// @generated by cargo xtask ocomp registry from registry/ocomp-v1.tsv.
// Do not edit by hand.

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum ObjectKind {
    ProtocolBundleV1 = 0x0001,
    CorrectnessProfileV1 = 0x0002,
    CapacityProfileV1 = 0x0003,
    PreAdmissionEnvelopeV1 = 0x0004,
    ActivationPreconditionsV1 = 0x0005,
    JobIntentV1 = 0x0006,
    FinalizedIntentProofV1 = 0x0007,
    InputManifestV1 = 0x0008,
    AuthenticatedInputChunkV1 = 0x0009,
    UnitSpecV1 = 0x000a,
    UnitArtifactV1 = 0x000b,
    ResultChunkV1 = 0x000c,
    LysisResultV1 = 0x000d,
    ActivationPayloadV1 = 0x000e,
    OcompCommitteeSnapshotV1 = 0x000f,
    OcompKeyRegistrationV1 = 0x0010,
    ExecutionCertificateV1 = 0x0011,
    PoCActivationV1 = 0x0012,
    ActiveGenerationV1 = 0x0013,
    AggregateActivationReceiptV1 = 0x0014,
    NodBatchReceiptV1 = 0x0015,
    ContributorReceiptV1 = 0x0016,
    TributeReceiptV1 = 0x0017,
    RequestBudgetSplitReceiptV1 = 0x0018,
    CarryOverReceiptV1 = 0x0019,
    CandidateAnnouncementV1 = 0x001a,
    SignOnceRecordV1 = 0x001b,
    ActivationCallCoreV1 = 0x001c,
    LysisArithmeticSummaryV1 = 0x001d,
    OcompJobRecordV1 = 0x001e,
}

impl ObjectKind {
    pub const ALL: &'static [Self] = &[
        Self::ProtocolBundleV1,
        Self::CorrectnessProfileV1,
        Self::CapacityProfileV1,
        Self::PreAdmissionEnvelopeV1,
        Self::ActivationPreconditionsV1,
        Self::JobIntentV1,
        Self::FinalizedIntentProofV1,
        Self::InputManifestV1,
        Self::AuthenticatedInputChunkV1,
        Self::UnitSpecV1,
        Self::UnitArtifactV1,
        Self::ResultChunkV1,
        Self::LysisResultV1,
        Self::ActivationPayloadV1,
        Self::OcompCommitteeSnapshotV1,
        Self::OcompKeyRegistrationV1,
        Self::ExecutionCertificateV1,
        Self::PoCActivationV1,
        Self::ActiveGenerationV1,
        Self::AggregateActivationReceiptV1,
        Self::NodBatchReceiptV1,
        Self::ContributorReceiptV1,
        Self::TributeReceiptV1,
        Self::RequestBudgetSplitReceiptV1,
        Self::CarryOverReceiptV1,
        Self::CandidateAnnouncementV1,
        Self::SignOnceRecordV1,
        Self::ActivationCallCoreV1,
        Self::LysisArithmeticSummaryV1,
        Self::OcompJobRecordV1,
    ];

    #[must_use]
    pub const fn tag(self) -> u16 {
        self as u16
    }

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::ProtocolBundleV1 => "ProtocolBundleV1",
            Self::CorrectnessProfileV1 => "CorrectnessProfileV1",
            Self::CapacityProfileV1 => "CapacityProfileV1",
            Self::PreAdmissionEnvelopeV1 => "PreAdmissionEnvelopeV1",
            Self::ActivationPreconditionsV1 => "ActivationPreconditionsV1",
            Self::JobIntentV1 => "JobIntentV1",
            Self::FinalizedIntentProofV1 => "FinalizedIntentProofV1",
            Self::InputManifestV1 => "InputManifestV1",
            Self::AuthenticatedInputChunkV1 => "AuthenticatedInputChunkV1",
            Self::UnitSpecV1 => "UnitSpecV1",
            Self::UnitArtifactV1 => "UnitArtifactV1",
            Self::ResultChunkV1 => "ResultChunkV1",
            Self::LysisResultV1 => "LysisResultV1",
            Self::ActivationPayloadV1 => "ActivationPayloadV1",
            Self::OcompCommitteeSnapshotV1 => "OcompCommitteeSnapshotV1",
            Self::OcompKeyRegistrationV1 => "OcompKeyRegistrationV1",
            Self::ExecutionCertificateV1 => "ExecutionCertificateV1",
            Self::PoCActivationV1 => "PoCActivationV1",
            Self::ActiveGenerationV1 => "ActiveGenerationV1",
            Self::AggregateActivationReceiptV1 => "AggregateActivationReceiptV1",
            Self::NodBatchReceiptV1 => "NodBatchReceiptV1",
            Self::ContributorReceiptV1 => "ContributorReceiptV1",
            Self::TributeReceiptV1 => "TributeReceiptV1",
            Self::RequestBudgetSplitReceiptV1 => "RequestBudgetSplitReceiptV1",
            Self::CarryOverReceiptV1 => "CarryOverReceiptV1",
            Self::CandidateAnnouncementV1 => "CandidateAnnouncementV1",
            Self::SignOnceRecordV1 => "SignOnceRecordV1",
            Self::ActivationCallCoreV1 => "ActivationCallCoreV1",
            Self::LysisArithmeticSummaryV1 => "LysisArithmeticSummaryV1",
            Self::OcompJobRecordV1 => "OcompJobRecordV1",
        }
    }
}

impl TryFrom<u16> for ObjectKind {
    type Error = crate::error::ProtocolError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0x0001 => Ok(Self::ProtocolBundleV1),
            0x0002 => Ok(Self::CorrectnessProfileV1),
            0x0003 => Ok(Self::CapacityProfileV1),
            0x0004 => Ok(Self::PreAdmissionEnvelopeV1),
            0x0005 => Ok(Self::ActivationPreconditionsV1),
            0x0006 => Ok(Self::JobIntentV1),
            0x0007 => Ok(Self::FinalizedIntentProofV1),
            0x0008 => Ok(Self::InputManifestV1),
            0x0009 => Ok(Self::AuthenticatedInputChunkV1),
            0x000a => Ok(Self::UnitSpecV1),
            0x000b => Ok(Self::UnitArtifactV1),
            0x000c => Ok(Self::ResultChunkV1),
            0x000d => Ok(Self::LysisResultV1),
            0x000e => Ok(Self::ActivationPayloadV1),
            0x000f => Ok(Self::OcompCommitteeSnapshotV1),
            0x0010 => Ok(Self::OcompKeyRegistrationV1),
            0x0011 => Ok(Self::ExecutionCertificateV1),
            0x0012 => Ok(Self::PoCActivationV1),
            0x0013 => Ok(Self::ActiveGenerationV1),
            0x0014 => Ok(Self::AggregateActivationReceiptV1),
            0x0015 => Ok(Self::NodBatchReceiptV1),
            0x0016 => Ok(Self::ContributorReceiptV1),
            0x0017 => Ok(Self::TributeReceiptV1),
            0x0018 => Ok(Self::RequestBudgetSplitReceiptV1),
            0x0019 => Ok(Self::CarryOverReceiptV1),
            0x001a => Ok(Self::CandidateAnnouncementV1),
            0x001b => Ok(Self::SignOnceRecordV1),
            0x001c => Ok(Self::ActivationCallCoreV1),
            0x001d => Ok(Self::LysisArithmeticSummaryV1),
            0x001e => Ok(Self::OcompJobRecordV1),
            value => Err(crate::error::ProtocolError::UnknownObjectKind(value)),
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum HashDomain {
    ProtocolBundle,
    PreAdmission,
    ActivationPreconditions,
    Intent,
    IntentSlot,
    Job,
    InputChunk,
    InputManifest,
    Plan,
    Unit,
    UnitInterval,
    UnitInputs,
    UnitEmpty,
    UnitOutput,
    UnitCoverage,
    UnitArtifact,
    ResultChunk,
    Result,
    ValidatorIdentity,
    Committee,
    KeyPop,
    SignOnceSlot,
    ActivationCall,
    LysisArithmetic,
    ResultEvidence,
    TerminalReceipt,
    NodReceipt,
    ContributorReceipt,
    TributeReceipt,
    DesisRequestBrief,
    BudgetSplitReceipt,
    CarryOverReceipt,
    ActiveGeneration,
    JobRecord,
    StateEvents,
    ApplyEventSummary,
    Effects,
    ListEmpty,
    ListLeaf,
    ListPad,
    ListNode,
    ListRoot,
}

impl HashDomain {
    pub const ALL: &'static [Self] = &[
        Self::ProtocolBundle,
        Self::PreAdmission,
        Self::ActivationPreconditions,
        Self::Intent,
        Self::IntentSlot,
        Self::Job,
        Self::InputChunk,
        Self::InputManifest,
        Self::Plan,
        Self::Unit,
        Self::UnitInterval,
        Self::UnitInputs,
        Self::UnitEmpty,
        Self::UnitOutput,
        Self::UnitCoverage,
        Self::UnitArtifact,
        Self::ResultChunk,
        Self::Result,
        Self::ValidatorIdentity,
        Self::Committee,
        Self::KeyPop,
        Self::SignOnceSlot,
        Self::ActivationCall,
        Self::LysisArithmetic,
        Self::ResultEvidence,
        Self::TerminalReceipt,
        Self::NodReceipt,
        Self::ContributorReceipt,
        Self::TributeReceipt,
        Self::DesisRequestBrief,
        Self::BudgetSplitReceipt,
        Self::CarryOverReceipt,
        Self::ActiveGeneration,
        Self::JobRecord,
        Self::StateEvents,
        Self::ApplyEventSummary,
        Self::Effects,
        Self::ListEmpty,
        Self::ListLeaf,
        Self::ListPad,
        Self::ListNode,
        Self::ListRoot,
    ];

    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProtocolBundle => "OUTBE_OCOMP_PROTOCOL_BUNDLE_V1",
            Self::PreAdmission => "OUTBE_OCOMP_PRE_ADMISSION_V1",
            Self::ActivationPreconditions => "OUTBE_OCOMP_ACTIVATION_PRECONDITIONS_V1",
            Self::Intent => "OUTBE_OCOMP_INTENT_V1",
            Self::IntentSlot => "OUTBE_OCOMP_INTENT_SLOT_V1",
            Self::Job => "OUTBE_OCOMP_JOB_V1",
            Self::InputChunk => "OUTBE_OCOMP_INPUT_CHUNK_V1",
            Self::InputManifest => "OUTBE_OCOMP_INPUT_MANIFEST_V1",
            Self::Plan => "OUTBE_OCOMP_PLAN_V1",
            Self::Unit => "OUTBE_OCOMP_UNIT_V1",
            Self::UnitInterval => "OUTBE_OCOMP_UNIT_INTERVAL_V1",
            Self::UnitInputs => "OUTBE_OCOMP_UNIT_INPUTS_V1",
            Self::UnitEmpty => "OUTBE_OCOMP_UNIT_EMPTY_V1",
            Self::UnitOutput => "OUTBE_OCOMP_UNIT_OUTPUT_V1",
            Self::UnitCoverage => "OUTBE_OCOMP_UNIT_COVERAGE_V1",
            Self::UnitArtifact => "OUTBE_OCOMP_UNIT_ARTIFACT_V1",
            Self::ResultChunk => "OUTBE_OCOMP_RESULT_CHUNK_V1",
            Self::Result => "OUTBE_OCOMP_RESULT_V1",
            Self::ValidatorIdentity => "OUTBE_OCOMP_VALIDATOR_IDENTITY_V1",
            Self::Committee => "OUTBE_OCOMP_COMMITTEE_V1",
            Self::KeyPop => "OUTBE_OCOMP_KEY_POP_V1",
            Self::SignOnceSlot => "OUTBE_OCOMP_SIGN_ONCE_SLOT_V1",
            Self::ActivationCall => "OUTBE_OCOMP_ACTIVATION_CALL_V1",
            Self::LysisArithmetic => "OUTBE_OCOMP_LYSIS_ARITHMETIC_V1",
            Self::ResultEvidence => "OUTBE_OCOMP_RESULT_EVIDENCE_V1",
            Self::TerminalReceipt => "OUTBE_OCOMP_TERMINAL_RECEIPT_V1",
            Self::NodReceipt => "OUTBE_OCOMP_NOD_RECEIPT_V1",
            Self::ContributorReceipt => "OUTBE_OCOMP_CONTRIBUTOR_RECEIPT_V1",
            Self::TributeReceipt => "OUTBE_OCOMP_TRIBUTE_RECEIPT_V1",
            Self::DesisRequestBrief => "OUTBE_OCOMP_DESIS_REQUEST_BRIEF_V1",
            Self::BudgetSplitReceipt => "OUTBE_OCOMP_BUDGET_SPLIT_RECEIPT_V1",
            Self::CarryOverReceipt => "OUTBE_OCOMP_CARRY_OVER_RECEIPT_V1",
            Self::ActiveGeneration => "OUTBE_OCOMP_ACTIVE_GENERATION_V1",
            Self::JobRecord => "OUTBE_OCOMP_JOB_RECORD_V1",
            Self::StateEvents => "OUTBE_OCOMP_STATE_EVENTS_V1",
            Self::ApplyEventSummary => "OUTBE_OCOMP_APPLY_EVENT_SUMMARY_V1",
            Self::Effects => "OUTBE_OCOMP_EFFECTS_V1",
            Self::ListEmpty => "OUTBE_OCOMP_LIST_EMPTY_V1",
            Self::ListLeaf => "OUTBE_OCOMP_LIST_LEAF_V1",
            Self::ListPad => "OUTBE_OCOMP_LIST_PAD_V1",
            Self::ListNode => "OUTBE_OCOMP_LIST_NODE_V1",
            Self::ListRoot => "OUTBE_OCOMP_LIST_ROOT_V1",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum ListKind {
    NodActions = 1,
    BucketRecords = 2,
    ContributorActions = 3,
    CompleteOutputManifest = 4,
    SemanticEventRecords = 5,
    InputChunkReferences = 6,
    UnitSpecificationsArtifacts = 7,
    RawTributeCoverage = 8,
}

impl ListKind {
    pub const ALL: &'static [Self] = &[
        Self::NodActions,
        Self::BucketRecords,
        Self::ContributorActions,
        Self::CompleteOutputManifest,
        Self::SemanticEventRecords,
        Self::InputChunkReferences,
        Self::UnitSpecificationsArtifacts,
        Self::RawTributeCoverage,
    ];

    #[must_use]
    pub const fn id(self) -> u16 {
        self as u16
    }

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::NodActions => "Nod actions",
            Self::BucketRecords => "bucket records",
            Self::ContributorActions => "contributor actions",
            Self::CompleteOutputManifest => "complete output manifest",
            Self::SemanticEventRecords => "semantic event records",
            Self::InputChunkReferences => "input chunk references",
            Self::UnitSpecificationsArtifacts => "unit specifications/artifacts",
            Self::RawTributeCoverage => "raw Tribute coverage (raw_ordinal, tribute_id)",
        }
    }
}

impl TryFrom<u16> for ListKind {
    type Error = crate::error::ProtocolError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::NodActions),
            2 => Ok(Self::BucketRecords),
            3 => Ok(Self::ContributorActions),
            4 => Ok(Self::CompleteOutputManifest),
            5 => Ok(Self::SemanticEventRecords),
            6 => Ok(Self::InputChunkReferences),
            7 => Ok(Self::UnitSpecificationsArtifacts),
            8 => Ok(Self::RawTributeCoverage),
            value => Err(crate::error::ProtocolError::UnknownListKind(value)),
        }
    }
}
