//! Economic expectations from fixture inputs, independent of runtime math.

use std::sync::LazyLock;

use alloy_primitives::U256;

const SECONDS_PER_DAY: u64 = 86_400;
const NATIVE_PER_PROTOCOL_UNIT: u64 = 1_000_000_000_000;

// Generated by testing/emission-reference/reference.py using 100-digit Decimal
// arithmetic. Do not replace this table with the production emission function.
static EMISSION_UNITS: LazyLock<Vec<U256>> = LazyLock::new(|| {
    let reference: serde_json::Value =
        serde_json::from_str(include_str!("../../../emission-reference/vectors.json"))
            .expect("independent emission reference JSON");
    assert_eq!(reference["schema"], "outbe-emission-scale6-v1");
    let days = reference["days"]
        .as_array()
        .expect("emission reference days");
    assert_eq!(days.len(), 3_073);
    days.iter()
        .enumerate()
        .map(|(index, day)| {
            assert_eq!(day["day"].as_u64(), Some(index as u64));
            U256::from_str_radix(
                day["emission_units"].as_str().expect("reference amount"),
                10,
            )
            .expect("reference emission fits U256")
        })
        .collect()
});

fn emission_units(day: u64) -> U256 {
    EMISSION_UNITS[day.min(3_072) as usize]
}

pub(crate) fn emission_day(genesis_timestamp: u64, timestamp: u64) -> u64 {
    (timestamp / SECONDS_PER_DAY)
        .checked_sub(genesis_timestamp / SECONDS_PER_DAY)
        .expect("economic observation predates genesis UTC day")
}

/// Each fixture has exactly one WAA beneficiary and one SRA beneficiary.
/// Each receives 32% of its 4% daily pool. Both floors precede conversion
/// from the six-decimal protocol unit to the native eighteen-decimal unit.
pub(crate) fn single_beneficiary_reward(day: u64) -> U256 {
    let pool = emission_units(day) * U256::from(4) / U256::from(100);
    let capped = pool * U256::from(32) / U256::from(100);
    capped * U256::from(NATIVE_PER_PROTOCOL_UNIT)
}

/// CCA receives its entire 4% pool for each UTC day closed between snapshots.
pub(crate) fn cca_accrual(first_day: u64, end_day: u64) -> U256 {
    assert!(end_day >= first_day, "CCA observation moved backwards");
    (first_day..end_day).fold(U256::ZERO, |sum, day| {
        let pool = emission_units(day) * U256::from(4) / U256::from(100);
        sum.checked_add(pool * U256::from(NATIVE_PER_PROTOCOL_UNIT))
            .expect("expected CCA accrual fits U256")
    })
}

/// Certified contributor batches can arrive in any order. Every leaf receives
/// its floored proportional share; the round burns the undistributed remainder.
pub(crate) fn contributor_shares(amount: U256, nominal: &[U256]) -> (Vec<U256>, U256) {
    assert!(
        !nominal.is_empty(),
        "expected contributor population is empty"
    );
    let total = nominal.iter().fold(U256::ZERO, |sum, value| {
        assert!(!value.is_zero(), "expected contributor nominal is zero");
        sum.checked_add(*value)
            .expect("expected nominal total fits U256")
    });
    let shares: Vec<_> = nominal
        .iter()
        .map(|value| {
            amount
                .checked_mul(*value)
                .expect("expected contributor share fits U256")
                / total
        })
        .collect();
    let paid = shares.iter().fold(U256::ZERO, |sum, share| {
        sum.checked_add(*share)
            .expect("expected paid total fits U256")
    });
    (
        shares,
        amount
            .checked_sub(paid)
            .expect("expected shares do not exceed proceeds"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy_primitives::uint;

    #[test]
    fn capped_reward_floors_before_native_conversion() {
        // Independent Decimal day-1 emission = 268480452713195;
        // floor(4% emission) = 10739218108527; floor(32% pool) = 3436549794728.
        assert_eq!(
            single_beneficiary_reward(1),
            uint!(3436549794728000000000000_U256)
        );
        assert_eq!(cca_accrual(1, 2), uint!(10739218108527000000000000_U256));
        assert_eq!(cca_accrual(1, 1), U256::ZERO);
        assert_eq!(
            single_beneficiary_reward(3_072),
            single_beneficiary_reward(9_999)
        );
    }

    #[test]
    fn emission_day_uses_utc_calendar_boundaries() {
        assert_eq!(emission_day(86_399, 86_400), 1);
        assert_eq!(emission_day(86_400, 172_799), 0);
        assert_eq!(cca_accrual(0, 2), cca_accrual(0, 1) + cca_accrual(1, 2));
    }

    #[test]
    fn contributor_flooring_keeps_dust_out_of_every_recipient() {
        let (shares, burned) = contributor_shares(U256::from(11), &[1, 2, 3].map(U256::from));
        assert_eq!(shares, [1, 3, 5].map(U256::from));
        assert_eq!(burned, U256::from(2));
        for (count, each, dust) in [(1, 1_000_000, 0), (10, 100_000, 0), (257, 3_891, 13)] {
            let (shares, burned) =
                contributor_shares(U256::from(1_000_000), &vec![U256::from(2_000_000); count]);
            assert_eq!(shares, vec![U256::from(each); count]);
            assert_eq!(burned, U256::from(dust));
        }
    }
}
