use std::{
    collections::BTreeSet,
    fmt::Write as _,
    path::{Path, PathBuf},
};

use eyre::{bail, ensure, Context, Result};

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
enum RowKind {
    Object,
    Domain,
    List,
}

impl RowKind {
    fn parse(value: &str) -> Result<Self> {
        match value {
            "object" => Ok(Self::Object),
            "domain" => Ok(Self::Domain),
            "list" => Ok(Self::List),
            value => bail!("unknown registry row type {value:?}"),
        }
    }

    const fn name(self) -> &'static str {
        match self {
            Self::Object => "object",
            Self::Domain => "domain",
            Self::List => "list",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct Row {
    kind: RowKind,
    identifier: String,
    variant: String,
    wire: String,
}

pub fn run(repository_root: &Path, check: bool) -> Result<()> {
    let crate_root = repository_root.join("crates/system/ocomp-protocol");
    let source = crate_root.join("registry/ocomp-v1.tsv");
    let rows = load_rows(&source)?;
    let outputs = [
        (
            crate_root.join("src/generated_registry.rs"),
            render_rust(&rows)?,
        ),
        (
            crate_root.join("registry/generated-registry.md"),
            render_docs(&rows),
        ),
    ];
    for (path, output) in outputs {
        update_or_check(repository_root, &path, output, check)?;
    }
    Ok(())
}

fn load_rows(path: &Path) -> Result<Vec<Row>> {
    let contents = std::fs::read_to_string(path)
        .wrap_err_with(|| format!("failed reading {}", path.display()))?;
    let mut lines = contents.lines();
    ensure!(
        lines.next() == Some("type\tid\tvariant\twire"),
        "unexpected OCOMP registry TSV header"
    );
    let mut rows = Vec::new();
    for (index, line) in lines.enumerate() {
        if line.is_empty() {
            continue;
        }
        let fields = line.split('\t').collect::<Vec<_>>();
        ensure!(
            fields.len() == 4,
            "registry line {} has {} fields, expected 4",
            index + 2,
            fields.len()
        );
        rows.push(Row {
            kind: RowKind::parse(fields[0])?,
            identifier: fields[1].to_owned(),
            variant: fields[2].to_owned(),
            wire: fields[3].to_owned(),
        });
    }
    validate_rows(&rows)?;
    Ok(rows)
}

fn validate_rows(rows: &[Row]) -> Result<()> {
    for kind in [RowKind::Object, RowKind::Domain, RowKind::List] {
        let selected = rows
            .iter()
            .filter(|row| row.kind == kind)
            .collect::<Vec<_>>();
        ensure!(!selected.is_empty(), "registry has no {} rows", kind.name());
        ensure_unique(
            kind,
            "variant",
            selected.iter().map(|row| row.variant.as_str()),
        )?;
        ensure_unique(kind, "wire", selected.iter().map(|row| row.wire.as_str()))?;
        ensure!(
            selected.iter().all(|row| row.wire.is_ascii()),
            "{} registry contains non-ASCII wire value",
            kind.name()
        );

        if kind == RowKind::Domain {
            ensure!(
                selected.iter().all(|row| row.identifier.is_empty()),
                "domain rows must not have numeric identifiers"
            );
        } else {
            let mut identifiers = BTreeSet::new();
            for row in selected {
                ensure!(
                    !row.identifier.is_empty(),
                    "{} row {} has no identifier",
                    kind.name(),
                    row.variant
                );
                let value = parse_identifier(&row.identifier)?;
                ensure!(
                    identifiers.insert(value),
                    "duplicate normalized {} identifier {}",
                    kind.name(),
                    row.identifier
                );
            }
        }
    }
    Ok(())
}

fn ensure_unique<'a>(
    kind: RowKind,
    field: &str,
    values: impl IntoIterator<Item = &'a str>,
) -> Result<()> {
    let mut seen = BTreeSet::new();
    for value in values {
        ensure!(
            seen.insert(value),
            "duplicate {} {field} {value:?}",
            kind.name()
        );
    }
    Ok(())
}

fn parse_identifier(value: &str) -> Result<u16> {
    let parsed = if let Some(hex) = value.strip_prefix("0x") {
        u16::from_str_radix(hex, 16)
    } else {
        value.parse()
    };
    parsed.wrap_err_with(|| format!("invalid u16 registry identifier {value:?}"))
}

fn render_rust(rows: &[Row]) -> Result<String> {
    let objects = rows_for(rows, RowKind::Object);
    let domains = rows_for(rows, RowKind::Domain);
    let lists = rows_for(rows, RowKind::List);
    let mut output = String::from(
        "// @generated by cargo xtask ocomp registry from registry/ocomp-v1.tsv.\n\
         // Do not edit by hand.\n\n",
    );
    output.push_str(&render_numeric_enum(
        "ObjectKind",
        "u16",
        &objects,
        "UnknownObjectKind",
        "tag",
    )?);
    output.push_str(
        "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\n\
         pub enum HashDomain {\n",
    );
    for row in &domains {
        writeln!(output, "    {},", row.variant)?;
    }
    output.push_str("}\n\nimpl HashDomain {\n    pub const ALL: &'static [Self] = &[\n");
    for row in &domains {
        writeln!(output, "        Self::{},", row.variant)?;
    }
    output.push_str(
        "    ];\n\n    #[must_use]\n    pub const fn as_str(self) -> &'static str {\n\
         \x20       match self {\n",
    );
    for row in &domains {
        writeln!(
            output,
            "            Self::{} => {:?},",
            row.variant, row.wire
        )?;
    }
    output.push_str("        }\n    }\n}\n\n");
    output.push_str(&render_numeric_enum(
        "ListKind",
        "u16",
        &lists,
        "UnknownListKind",
        "id",
    )?);
    Ok(output)
}

fn render_numeric_enum(
    name: &str,
    repr_type: &str,
    rows: &[&Row],
    unknown_error: &str,
    id_method: &str,
) -> Result<String> {
    let mut output = format!(
        "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\n\
         #[repr({repr_type})]\n\
         pub enum {name} {{\n"
    );
    for row in rows {
        writeln!(output, "    {} = {},", row.variant, row.identifier)?;
    }
    writeln!(
        output,
        "}}\n\nimpl {name} {{\n    pub const ALL: &'static [Self] = &["
    )?;
    for row in rows {
        writeln!(output, "        Self::{},", row.variant)?;
    }
    write!(
        output,
        "    ];\n\n    #[must_use]\n    pub const fn {id_method}(self) -> {repr_type} {{\n\
         \x20       self as {repr_type}\n\
         \x20   }}\n\n\
         \x20   #[must_use]\n\
         \x20   pub const fn name(self) -> &'static str {{\n\
         \x20       match self {{\n"
    )?;
    for row in rows {
        writeln!(
            output,
            "            Self::{} => {:?},",
            row.variant, row.wire
        )?;
    }
    write!(
        output,
        "        }}\n    }}\n}}\n\n\
         impl TryFrom<{repr_type}> for {name} {{\n\
         \x20   type Error = crate::error::ProtocolError;\n\n\
         \x20   fn try_from(value: {repr_type}) -> Result<Self, Self::Error> {{\n\
         \x20       match value {{\n"
    )?;
    for row in rows {
        writeln!(
            output,
            "            {} => Ok(Self::{}),",
            row.identifier, row.variant
        )?;
    }
    write!(
        output,
        "            value => Err(crate::error::ProtocolError::{unknown_error}(value)),\n\
         \x20       }}\n    }}\n}}\n"
    )?;
    Ok(output)
}

fn render_docs(rows: &[Row]) -> String {
    let mut output = String::from(
        "<!-- @generated by cargo xtask ocomp registry; do not edit. -->\n\
         # OCOMP V1 generated registry\n\n",
    );
    let sections = [
        (RowKind::Object, "Object kinds"),
        (RowKind::Domain, "Hash domains"),
        (RowKind::List, "Ordered-list kinds"),
    ];
    let section_count = sections.len();
    for (section_index, (kind, title)) in sections.into_iter().enumerate() {
        writeln!(
            output,
            "## {title}\n\n| ID | Rust variant | Wire value |\n|---:|---|---|"
        )
        .expect("writing to String cannot fail");
        for row in rows.iter().filter(|row| row.kind == kind) {
            let identifier = if row.identifier.is_empty() {
                "—".to_owned()
            } else {
                format!("`{}`", row.identifier)
            };
            writeln!(
                output,
                "| {identifier} | `{}` | `{}` |",
                row.variant, row.wire
            )
            .expect("writing to String cannot fail");
        }
        if section_index + 1 < section_count {
            output.push('\n');
        }
    }
    output
}

fn rows_for(rows: &[Row], kind: RowKind) -> Vec<&Row> {
    rows.iter().filter(|row| row.kind == kind).collect()
}

fn update_or_check(repository_root: &Path, path: &Path, output: String, check: bool) -> Result<()> {
    let mut expected = output;
    if !expected.ends_with('\n') {
        expected.push('\n');
    }
    let actual = std::fs::read_to_string(path).ok();
    if actual.as_deref() == Some(expected.as_str()) {
        return Ok(());
    }
    let display = relative_path(repository_root, path);
    if check {
        bail!("stale generated OCOMP registry: {}", display.display());
    }
    std::fs::write(path, expected)
        .wrap_err_with(|| format!("failed writing {}", path.display()))?;
    println!("wrote {}", display.display());
    Ok(())
}

fn relative_path(repository_root: &Path, path: &Path) -> PathBuf {
    path.strip_prefix(repository_root)
        .unwrap_or(path)
        .to_path_buf()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn numeric_collisions_are_normalized() {
        let rows = [
            Row {
                kind: RowKind::Object,
                identifier: "1".to_owned(),
                variant: "One".to_owned(),
                wire: "One".to_owned(),
            },
            Row {
                kind: RowKind::Object,
                identifier: "0x0001".to_owned(),
                variant: "AlsoOne".to_owned(),
                wire: "AlsoOne".to_owned(),
            },
            Row {
                kind: RowKind::Domain,
                identifier: String::new(),
                variant: "Domain".to_owned(),
                wire: "DOMAIN_V1".to_owned(),
            },
            Row {
                kind: RowKind::List,
                identifier: "1".to_owned(),
                variant: "List".to_owned(),
                wire: "list".to_owned(),
            },
        ];
        assert!(validate_rows(&rows)
            .unwrap_err()
            .to_string()
            .contains("duplicate normalized object identifier"));
    }

    #[test]
    fn checked_in_registry_is_current() {
        run(&crate::release::sgx::repository_root().unwrap(), true).unwrap();
    }
}
