#!/usr/bin/env python3
"""Generate the Rust and Markdown OCOMP registries from one TSV authority."""

from __future__ import annotations

import argparse
import csv
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "registry" / "ocomp-v1.tsv"
RUST_OUTPUT = ROOT / "src" / "generated_registry.rs"
DOC_OUTPUT = ROOT / "registry" / "generated-registry.md"


@dataclass(frozen=True)
class Row:
    kind: str
    identifier: str
    variant: str
    wire: str


def load_rows() -> list[Row]:
    with SOURCE.open(encoding="utf-8", newline="") as source:
        reader = csv.DictReader(source, delimiter="\t")
        expected = ["type", "id", "variant", "wire"]
        if reader.fieldnames != expected:
            raise ValueError(f"expected TSV columns {expected}, got {reader.fieldnames}")
        rows = [
            Row(
                kind=row["type"],
                identifier=row["id"],
                variant=row["variant"],
                wire=row["wire"],
            )
            for row in reader
        ]

    allowed = {"object", "domain", "list"}
    unexpected = sorted({row.kind for row in rows} - allowed)
    if unexpected:
        raise ValueError(f"unknown registry row types: {unexpected}")
    for kind in sorted(allowed):
        selected = [row for row in rows if row.kind == kind]
        if not selected:
            raise ValueError(f"registry has no {kind} rows")
        variants = [row.variant for row in selected]
        wires = [row.wire for row in selected]
        if len(variants) != len(set(variants)):
            raise ValueError(f"duplicate {kind} variant")
        if len(wires) != len(set(wires)):
            raise ValueError(f"duplicate {kind} wire value")
        identifiers = [row.identifier for row in selected if row.identifier]
        if len(identifiers) != len(set(identifiers)):
            raise ValueError(f"duplicate {kind} identifier")
    return rows


def rust_enum(
    name: str,
    repr_type: str,
    rows: list[Row],
    id_expression,
    unknown_error: str,
    id_method: str,
) -> str:
    variants = "\n".join(
        f"    {row.variant} = {id_expression(row)}," for row in rows
    )
    all_values = "\n".join(f"        Self::{row.variant}," for row in rows)
    names = "\n".join(
        f'            Self::{row.variant} => "{row.wire}",' for row in rows
    )
    conversions = "\n".join(
        f"            {id_expression(row)} => Ok(Self::{row.variant})," for row in rows
    )
    error_value = "value" if repr_type == "u16" else "u16::from(value)"
    return f"""#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr({repr_type})]
pub enum {name} {{
{variants}
}}

impl {name} {{
    pub const ALL: &'static [Self] = &[
{all_values}
    ];

    #[must_use]
    pub const fn {id_method}(self) -> {repr_type} {{
        self as {repr_type}
    }}

    #[must_use]
    pub const fn name(self) -> &'static str {{
        match self {{
{names}
        }}
    }}
}}

impl TryFrom<{repr_type}> for {name} {{
    type Error = crate::error::ProtocolError;

    fn try_from(value: {repr_type}) -> Result<Self, Self::Error> {{
        match value {{
{conversions}
            value => Err(crate::error::ProtocolError::{unknown_error}({error_value})),
        }}
    }}
}}
"""


def render_rust(rows: list[Row]) -> str:
    objects = [row for row in rows if row.kind == "object"]
    domains = [row for row in rows if row.kind == "domain"]
    lists = [row for row in rows if row.kind == "list"]
    object_enum = rust_enum(
        "ObjectKind",
        "u16",
        objects,
        lambda row: row.identifier,
        "UnknownObjectKind",
        "tag",
    )
    list_enum = rust_enum(
        "ListKind",
        "u16",
        lists,
        lambda row: row.identifier,
        "UnknownListKind",
        "id",
    )
    domain_variants = "\n".join(f"    {row.variant}," for row in domains)
    domain_all = "\n".join(f"        Self::{row.variant}," for row in domains)
    domain_names = "\n".join(
        f'            Self::{row.variant} => "{row.wire}",' for row in domains
    )
    return f"""// @generated by registry/generate.py from registry/ocomp-v1.tsv.
// Do not edit by hand.

{object_enum}
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum HashDomain {{
{domain_variants}
}}

impl HashDomain {{
    pub const ALL: &'static [Self] = &[
{domain_all}
    ];

    #[must_use]
    pub const fn as_str(self) -> &'static str {{
        match self {{
{domain_names}
        }}
    }}
}}

{list_enum}"""


def render_docs(rows: list[Row]) -> str:
    sections: list[str] = [
        "<!-- @generated by registry/generate.py; do not edit. -->",
        "# OCOMP V1 generated registry",
        "",
    ]
    for kind, title in (
        ("object", "Object kinds"),
        ("domain", "Hash domains"),
        ("list", "Ordered-list kinds"),
    ):
        sections.extend((f"## {title}", "", "| ID | Rust variant | Wire value |", "|---:|---|---|"))
        for row in rows:
            if row.kind == kind:
                identifier = f"`{row.identifier}`" if row.identifier else "—"
                sections.append(f"| {identifier} | `{row.variant}` | `{row.wire}` |")
        sections.append("")
    return "\n".join(sections)


def update_or_check(path: Path, expected: str, check: bool) -> bool:
    expected_bytes = (expected.rstrip() + "\n").encode()
    actual = path.read_bytes() if path.exists() else None
    if actual == expected_bytes:
        return True
    if check:
        print(f"stale generated registry: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.write_bytes(expected_bytes)
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rows = load_rows()
    checks = [
        update_or_check(RUST_OUTPUT, render_rust(rows), arguments.check),
        update_or_check(DOC_OUTPUT, render_docs(rows), arguments.check),
    ]
    return 0 if all(checks) else 1


if __name__ == "__main__":
    raise SystemExit(main())
