import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

/** ABI exports the server reads, rewritten as `as const` modules so viem can type each call. */
const SOURCES = ["intent", "intex", "precompiles", "tokens"];
const contracts = new URL("../../contracts/", import.meta.url).pathname;
const out = new URL("../src/abi/generated/", import.meta.url).pathname;

/** Replaces `path` in one rename, so a concurrent run or reader never sees a half-written module. */
function writeIfChanged(path: string, content: string): void {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return;
  const temp = `${path}.${process.pid}.tmp`;
  writeFileSync(temp, content);
  renameSync(temp, path);
}

for (const source of SOURCES) {
  const dir = join(contracts, source, "abi-export");
  const target = join(out, source);
  mkdirSync(target, { recursive: true });
  const modules = new Set<string>();
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const json: unknown = JSON.parse(readFileSync(join(dir, file), "utf8"));
    const abi = Array.isArray(json) ? json : (json as { abi: unknown }).abi;
    const name = `${basename(file, ".json")}.ts`;
    modules.add(name);
    writeIfChanged(
      join(target, name),
      `// Generated by scripts/gen-abi.ts from contracts/${source}/abi-export/${file}. Do not edit.\n` +
        `export default ${JSON.stringify(abi, null, 2)} as const;\n`,
    );
  }
  for (const stale of readdirSync(target).filter((f) => f.endsWith(".ts") && !modules.has(f))) {
    rmSync(join(target, stale), { force: true });
  }
}
