import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

/** ABI exports the server reads, rewritten as `as const` modules so viem can type each call. */
const SOURCES = ["intent", "intex", "precompiles", "tokens"];
const contracts = new URL("../../contracts/", import.meta.url).pathname;
const out = new URL("../src/abi/generated/", import.meta.url).pathname;

rmSync(out, { recursive: true, force: true });
for (const source of SOURCES) {
  const dir = join(contracts, source, "abi-export");
  mkdirSync(join(out, source), { recursive: true });
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const json: unknown = JSON.parse(readFileSync(join(dir, file), "utf8"));
    const abi = Array.isArray(json) ? json : (json as { abi: unknown }).abi;
    const module =
      `// Generated by scripts/gen-abi.ts from contracts/${source}/abi-export/${file}. Do not edit.\n` +
      `export default ${JSON.stringify(abi, null, 2)} as const;\n`;
    writeFileSync(join(out, source, `${basename(file, ".json")}.ts`), module);
  }
}
