[package]
name = "outbe-snapshot"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
hex.workspace = true
k256.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
