//! Frozen byte-vector regression for the V2 Hybrid certificate wire codec.
//!
//! These vectors are byte-identical to the encoder output that lived in
//! `outbe-consensus::hybrid` before the wire codec moved into this crate
//! (commit history can be checked against `git show <pre-move>:crates/blockchain/consensus/src/hybrid.rs`).
//!
//! The vectors are generated with deterministic BLS seeds so they are
//! reproducible from `cargo test --test codec_compat -- --nocapture` if the
//! `OUTBE_REGENERATE_LEGACY_VECTORS` env is set (no Cargo helper exposed by
//! design: regeneration is a manual, audited action).
//!
//! Any change here changes the on-chain block hash. Do not regenerate without
//! a coordinated rollout.

use commonware_codec::Encode;
use commonware_cryptography::{
    bls12381::{
        primitives::{
            ops::{aggregate, keypair, sign_message},
            variant::{MinPk, MinSig},
        },
        PrivateKey,
    },
    certificate::Signers,
    Signer,
};
use commonware_utils::Participant;
use outbe_consensus::proof::{HybridCertificate, VrfProof};
use rand::SeedableRng;
use rand_chacha::ChaCha20Rng;

/// Deterministic constructor: n=4 participants, signer indices {0, 2, 3},
/// VRF present with material version = 1 and a MinSig key seeded from 7.
///
/// The exact byte vector below was produced by encoding this certificate with
/// the pre-move `outbe-consensus::hybrid` encoder and verified to equal the
/// post-move `outbe-consensus-proof::hybrid_wire` encoder output.
fn legacy_fixture() -> HybridCertificate<MinSig> {
    let signers = Signers::from(4, [0u32, 2, 3].into_iter().map(Participant::new));

    let sigs: Vec<_> = [0u32, 2, 3]
        .into_iter()
        .map(|i| {
            let sk = PrivateKey::from_seed(i as u64 + 1);
            sk.sign(b"hybrid_codec_compat", b"vote")
        })
        .collect();
    let bls_aggregated_vote =
        aggregate::combine_signatures::<MinPk, _>(sigs.iter().map(|s| s.as_ref()));

    let mut rng = ChaCha20Rng::seed_from_u64(7);
    let (private, _public) = keypair::<_, MinSig>(&mut rng);
    let threshold_signature = sign_message::<MinSig>(&private, b"OUTBE_VRF_SEED_V2", b"compat");
    let vrf_proof = Some(VrfProof::<MinSig> {
        material_version: 1,
        threshold_signature,
    });

    HybridCertificate {
        signers,
        bls_aggregated_vote,
        vrf_proof,
    }
}

/// The frozen encoder output of `legacy_fixture()`. Generated by the BLS
/// signature primitives (deterministic given fixed seeds) and verified
/// byte-equal against the pre-move encoder. Any drift breaks block hashes.
const LEGACY_HYBRID_CERTIFICATE_HEX: &str =
    include_str!("proof_vectors/legacy_hybrid_certificate.hex");

#[test]
fn consensus_proof_codec_matches_legacy_hybrid_certificate_vectors() {
    let cert = legacy_fixture();
    let encoded = cert.encode();
    let actual_hex = hex_encode(encoded.as_ref());
    let expected_hex = LEGACY_HYBRID_CERTIFICATE_HEX.trim();
    assert_eq!(
        actual_hex.as_str(),
        expected_hex,
        "wire codec drifted; new vs legacy hex differ. If this is intentional, \
         regenerate vectors/legacy_hybrid_certificate.hex and ship the change as a \
         hard-fork-coordinated wire-format update.",
    );
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}
