[package]
name = "outbe-common"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
alloy-primitives.workspace = true
base64.workspace = true
ring.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
